### ISSUE TITLE
1.2 compatibility

### ISSUE THREAD

**Issue by bitwise-operators** [workos/workos-php-laravel#18]
This package specifies requiring version 1.0.0 exactly of the main workos/workos-php package.

Is there a reason why this isn't ^1.0.0?

I'm asking since the main package is currently at 1.2.0, and I don't see any major changes in the API since 1.0.0

**Comment by timmaybrown** [comment]
I'm running into an issue related to the above question, because the version is pinned directly to version `1.3.0` of the `workos-inc/workos-php` package when installing this package. 

Following along with [the docs](https://workos.com/docs/admin-portal/guide/real-time-updates-with-webhooks/receive-events/process-the-request) on using the SDK to validate the webhook payload isn't possible because the `WorkOs\Webhook()` class is missing.

Trying to workaround the issue/manually require `workos-php@1.6` fails as expected with the following error:
```
Problem 1
    - workos/workos-php-laravel v1.1.0 requires workos/workos-php 1.3.0 -> satisfiable by workos/workos-php[v1.3.0] but these conflict with your requirements or minimum-stability.
```

**Comment by timmaybrown** [comment]
@sheldonvaughn  - I didn't see this PR (https://github.com/workos-inc/workos-php-laravel/pull/21) when I made the above comments. Any chance this could be merged and this package's version bumped and pushed out so we can utilize the most recent version? 

There may be reasons, that I'm not aware of, but is there any reason that version pattern couldn't be
```
"workos/workos-php": "^1.6.0"
```
instead of pinned directly to the version so that we can install the minor version updates that happen to `workos-php` without having to have this package's version bumped.

Thanks!

**Comment by sheldonvaughn** [comment]
Hi All - thanks for the feedback - we've made this change so I'll go ahead and close this issue! Please don't hesitate to reach out with any additional requests.
